version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres_con
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: matchodds_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8089:8089"
    depends_on:
      - postgres
